// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6JQx0O4z9fw_QHAnBNxdblHUA6i2zzNg',
    appId: '1:860276803186:web:27d4fbf149a03e9ae124eb',
    messagingSenderId: '860276803186',
    projectId: 'news-b7c51',
    authDomain: 'news-b7c51.firebaseapp.com',
    storageBucket: 'news-b7c51.firebasestorage.app',
    measurementId: 'G-SNDF19HSH5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8CvDJb5RVoukBSDdvvN0uAvPacVIHtw4',
    appId: '1:860276803186:android:d6bdd9d67d04dda9e124eb',
    messagingSenderId: '860276803186',
    projectId: 'news-b7c51',
    storageBucket: 'news-b7c51.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrR8kiyozdNao96_Ek-NaiuiY6IyCjLdw',
    appId: '1:860276803186:ios:77fd80a0d4bf118ce124eb',
    messagingSenderId: '860276803186',
    projectId: 'news-b7c51',
    storageBucket: 'news-b7c51.firebasestorage.app',
    iosBundleId: 'com.example.newsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrR8kiyozdNao96_Ek-NaiuiY6IyCjLdw',
    appId: '1:860276803186:ios:77fd80a0d4bf118ce124eb',
    messagingSenderId: '860276803186',
    projectId: 'news-b7c51',
    storageBucket: 'news-b7c51.firebasestorage.app',
    iosBundleId: 'com.example.newsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6JQx0O4z9fw_QHAnBNxdblHUA6i2zzNg',
    appId: '1:860276803186:web:9b0b24ae202312cfe124eb',
    messagingSenderId: '860276803186',
    projectId: 'news-b7c51',
    authDomain: 'news-b7c51.firebaseapp.com',
    storageBucket: 'news-b7c51.firebasestorage.app',
    measurementId: 'G-Q61TEKP4ZG',
  );
}
